import HeroImage from "/assets/hero-img.webp";

const Image = {
  HeroImage,
};

export default Image;

import Tools1 from "/assets/tools/vscode.png";
import Tools2 from "/assets/tools/reactjs.png";
import Tools3 from "/assets/tools/nextjs.png";
import Tools4 from "/assets/tools/tailwind.png";
import Tools5 from "/assets/tools/bootstrap.png";
import Tools6 from "/assets/tools/js.png";
import Tools7 from "/assets/tools/nodejs.png";
import Tools8 from "/assets/tools/github.png";
import Tools9 from "/assets/tools/ai.png";
import Tools10 from "/assets/tools/canva.png";
import Tools11 from "/assets/tools/figma.png";
import Tools12 from "/assets/tools/kotlin.png";
import Tools13 from "/assets/tools/firebase.png";
import Tools14 from "/assets/tools/html.png";
import Tools15 from "/assets/tools/css.png";
import Tools16 from "/assets/tools/ts.png";
import Tools17 from "/assets/tools/php.png";
import Tools18 from "/assets/tools/vite.png";
import Tools19 from "/assets/tools/mysql.png";


export const listTools = [
  {
    id: 1,
    gambar: Tools1,
    nama: "Visual Studio Code",
    ket: "Code Editor",
    dad: "100",
  },
  {
    id: 2,
    gambar: Tools2,
    nama: "React JS",
    ket: "Framework",
    dad: "200",
  },
  {
    id: 3,
    gambar: Tools3,
    nama: "Next JS",
    ket: "Framework",
    dad: "300",
  },
  {
    id: 4,
    gambar: Tools4,
    nama: "Tailwind CSS",
    ket: "Framework",
    dad: "400",
  },
  {
    id: 5,
    gambar: Tools5,
    nama: "Bootstrap",
    ket: "Framework",
    dad: "500",
  },
  {
    id: 6,
    gambar: Tools6,
    nama: "Javascript",
    ket: "Language",
    dad: "600",
  },
  {
    id: 7,
    gambar: Tools7,
    nama: "Node JS",
    ket: "Javascript Runtime",
    dad: "700",
  },
  {
    id: 8,
    gambar: Tools8,
    nama: "Github",
    ket: "Repository",
    dad: "800",
  },
  {
    id: 9,
    gambar: Tools9,
    nama: "Adobe Illustrator",
    ket: "Design App",
    dad: "900",
  },
  {
    id: 10,
    gambar: Tools10,
    nama: "Canva",
    ket: "Design App",
    dad: "1000",
  },
  {
    id: 11,
    gambar: Tools11,
    nama: "Figma",
    ket: "Design App",
    dad: "1100",
  },
  {
    id: 12,
    gambar: Tools12,
    nama: "Kotlin",
    ket: "Language",
    dad: "1200",
  },
  {
    id: 13,
    gambar: Tools13,
    nama: "Firebase",
    ket: "Framework",
    dad: "1300",
  },
  {
    id: 14,
    gambar: Tools14,
    nama: "HTML",
    ket: "Language",
    dad: "1400",
  },
  {
    id: 15,
    gambar: Tools15,
    nama: "CSS",
    ket: "Language",
    dad: "1500",
  },
  {
    id: 16,
    gambar: Tools16,
    nama: "TypeScript",
    ket: "Language",
    dad: "1600",
  },
  {
    id: 17,
    gambar: Tools17,
    nama: "PHP",
    ket: "Language",
    dad: "1700",
  },
  {
    id: 18,
    gambar: Tools18,
    nama: "Vite",
    ket: "Framework",
    dad: "1800",
  },
  {
    id: 19,
    gambar: Tools19,
    nama: "MySql",
    ket: "Framework",
    dad: "1900",
  },
];

import Proyek1 from "/assets/proyek/proyek1.jpg";
import Proyek2 from "/assets/proyek/proyek2.jpg";
import Proyek3 from "/assets/proyek/proyek3.jpg";
import Proyek4 from "/assets/proyek/proyek4.jpg";
import Proyek5 from "/assets/proyek/proyek5.jpg";
import Proyek6 from "/assets/proyek/proyek6.jpg";

export const listProyek = [
  {
    id: 1,
    image: Proyek1,
    title: "Alokasi Overstok",
    subtitle: "Manajemen dan alokasi barang overstok secara efisien",
    fullDescription:
      "Manajemen dan alokasi barang overstok secara efisien",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://moonlit-gecko-1ab281.netlify.app/",
    dad: "100",
  },
  {
    id: 2,
    image: Proyek2,
    title: "SteamBox",
    subtitle: "Portal utilitas dan tools SteamBox",
    fullDescription: "Portal utilitas dan tools SteamBox",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://dracin-babyland.vercel.app/",
    dad: "200",
  },
  {
    id: 3,
    image: Proyek3,
    title: "Template Alokasi Barang",
    subtitle: "Template alokasi & manajemen stok gudang",
    fullDescription: "Template alokasi & manajemen stok gudang",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://funny-twilight-48b5c4.netlify.app/",
    dad: "300",
  },
  {
    id: 4,
    image: Proyek4,
    title: "Cek Pendingan",
    subtitle: "Mengecek status pendingan pemenuhan",
    fullDescription: "Mengecek status pendingan pemenuhan",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://sage-conkies-fd072b.netlify.app/",
    dad: "400",
  },
  {
    id: 5,
    image: Proyek5,
    title: "Table to Email",
    subtitle: "Konversi tabel HTML ke format email",
    fullDescription: "Konversi tabel HTML ke format email",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://tabletoemail.netlify.app/",
    dad: "500",
  },
  {
    id: 6,
    image: Proyek6,
    title: "PO Direct",
    subtitle: "Splitter PO untuk manajemen pesanan",
    fullDescription: "Splitter PO untuk manajemen pesanan",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://podirect.netlify.app/",
    dad: "600",
  },
  {
    id: 7,
    image: Proyek1,
    title: "PO Auto Reader",
    subtitle: "Baca & proses file PO otomatis",
    fullDescription: "Baca & proses file PO otomatis",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://po-auto-reader.netlify.app/",
    dad: "700",
  },
  {
    id: 8,
    image: Proyek2,
    title: "Split Excel",
    subtitle: "Memecah file Excel per kolom",
    fullDescription: "Memecah file Excel per kolom",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://tesxls.netlify.app/",
    dad: "800",
  },
  {
    id: 9,
    image: Proyek3,
    title: "Upload Data Excel",
    subtitle: "Kelola & lihat data Excel",
    fullDescription: "Kelola & lihat data Excel",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://andricris.github.io/data-excel/",
    dad: "900",
  },
  {
    id: 10,
    image: Proyek4,
    title: "Fake Strava",
    subtitle: "Generator GPX lari simulasi",
    fullDescription: "Generator GPX lari simulasi",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://fakeh3.netlify.app/",
    dad: "1000",
  },
  {
    id: 11,
    image: Proyek5,
    title: "Kalkulator ED Hibrida",
    subtitle: "Kalkulator hybrid ED",
    fullDescription: "Kalkulator hybrid ED",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://kalkuede.netlify.app/",
    dad: "1100",
  },
  {
    id: 12,
    image: Proyek6,
    title: "H3 Store",
    subtitle: "Toko online solusi digital",
    fullDescription: "Toko online solusi digital",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://newh3store.netlify.app/",
    dad: "1200",
  },
  {
    id: 13,
    image: Proyek1,
    title: "Kalkulator Umur",
    subtitle: "Hitung umur, shio, weton",
    fullDescription: "Hitung umur, shio, weton",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://kalmur.netlify.app/",
    dad: "1300",
  },
  {
    id: 14,
    image: Proyek2,
    title: "Kalkulator ED Single",
    subtitle: "Kalkulator nilai & EXP",
    fullDescription: "Kalkulator nilai & EXP",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://kalexp.netlify.app/",
    dad: "1400",
  },
  {
    id: 15,
    image: Proyek3,
    title: "Cons Dropping",
    subtitle: "Analisis & konsolidasi dropping",
    fullDescription: "Analisis & konsolidasi dropping",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://consdroping.netlify.app/",
    dad: "1500",
  },
  {
    id: 16,
    image: Proyek4,
    title: "Qris Pembayaran",
    subtitle: "Generator QRIS pembayaran",
    fullDescription: "Generator QRIS pembayaran",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://qrish3.netlify.app/",
    dad: "1600",
  },
  {
    id: 17,
    image: Proyek5,
    title: "Excel Line Converter",
    subtitle: "Baris Excel → satu baris",
    fullDescription: "Baris Excel → satu baris",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://exline.netlify.app/",
    dad: "1700",
  },
  {
    id: 18,
    image: Proyek6,
    title: "Migrasi CSV",
    subtitle: "Migrasi & proses CSV",
    fullDescription: "Migrasi & proses CSV",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://astounding-entremet-ae6f90.netlify.app/",
    dad: "1800",
  },
  {
    id: 19,
    image: Proyek1,
    title: "Data Tabular",
    subtitle: "Tabel data interaktif",
    fullDescription: "Tabel data interaktif",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://datatabular.netlify.app/",
    dad: "1900",
  },
  {
    id: 20,
    image: Proyek2,
    title: "Excel to JSON",
    subtitle: "Konversi Excel ke JSON",
    fullDescription: "Konversi Excel ke JSON",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://excelkejson.netlify.app/",
    dad: "2000",
  },
  {
    id: 21,
    image: Proyek3,
    title: "Excel Multi Column Pivot",
    subtitle: "Pivot multi-kolom dinamis",
    fullDescription: "Pivot multi-kolom dinamis",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://excel-multi-column-pivot.netlify.app/",
    dad: "2100",
  },
  {
    id: 22,
    image: Proyek4,
    title: "Kalkulator Kubikasi Berat",
    subtitle: "Hitung kubikasi berat logistik",
    fullDescription: "Hitung kubikasi berat logistik",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://kubikasi-berat.netlify.app/",
    dad: "2200",
  },
  {
    id: 23,
    image: Proyek5,
    title: "Kalkulator Rasio",
    subtitle: "Hitung rasio proporsional",
    fullDescription: "Hitung rasio proporsional",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://kalrasio.netlify.app/",
    dad: "2300",
  },
  {
    id: 24,
    image: Proyek6,
    title: "Jadwal Kirim & PL",
    subtitle: "Jadwal kirim & pick-up list",
    fullDescription: "Jadwal kirim & pick-up list",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://jadwlkrimdanpl.netlify.app/",
    dad: "2400",
  },
  {
    id: 25,
    image: Proyek1,
    title: "JPG to Txt",
    subtitle: "OCR JPG ke TXT via API",
    fullDescription: "OCR JPG ke TXT via API",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://ttdwnlodr.netlify.app/",
    dad: "2500",
  },
];
